---
- include: dependencies.yml
- include: db.yml

- name: Check out thredded code
  git: repo=https://github.com/jayroh/thredded_app.git dest=$thredded_path

- name: Add thredded_resque gem
  lineinfile: dest=$thredded_path/Gemfile state=present line="gem 'thredded_resque'" regexp="^gem 'thredded_resque'"

# Cannot use --deployment without thredded_resque being in Gemfile.lock already
- name: Bundle install
  command: $ruby_location/bin/bundle install chdir=$thredded_path

- name: Create config/database.yml
  template: src=database.yml.j2 dest=$thredded_path/config/database.yml

- name: Generate binstub
  shell: chdir=$thredded_path $ruby_location/bin/bundle binstub rake

- name: Generate secret token
  shell: cd $thredded_path && RAILS_ENV=production PATH=$ruby_location/bin:$PATH bin/rake secret
  register: thredded_secret_token

- name: Save secret token
  template: src=secret_token.rb.j2 dest=$thredded_path/config/initializers/secret_token.rb

- name: Migrate thredded DB
  shell: cd $thredded_path && RAILS_ENV=production PATH=$ruby_location/bin:$PATH bin/rake db:migrate

- name: Precompile assets
  shell: cd $thredded_path && RAILS_ENV=production PATH=$ruby_location/bin:$PATH bin/rake assets:precompile

- include: resque.yml
- include: nginx.yml
- include: passenger.yml
