development:
  adapter: postgresql
  encoding: unicode
  database: thredded_dev
  username: username
  password: password
  host: localhost
  port: 5432

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: silent

production:
  adapter: postgresql
  encoding: unicode
  database: thredded_production
  username: username
  password: password
  host: localhost
  port: 5432

