defaults: &defaults
  adapter: postgresql
  encoding: UTF8
  host: localhost
  port: 5432
  
development:
  <<: *defaults
  database: thredded_dev
  username: username
  password: password

test:
  <<: *defaults
  database: thredded_test
  username: username
  password: password

production:
  <<: *defaults
  database: thredded_production
  username: username
  password: password
