development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thredded_dev
  pool: 5
  username: username
  password: password
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thredded_test
  pool: 5
  username: username
  password: password
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thredded_production
  pool: 5
  username: username
  password: password
  socket: /tmp/mysql.sock
