defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *defaults
  database: thredded_dev
  username: username
  password: password

test:
  <<: *defaults
  database: thredded_test
  username: username
  password: password

test:
  <<: *defaults
  database: thredded_production
  username: username
  password: password
