development:
  adapter: postgresql
  encoding: UTF8
  database: thredded_dev
  username: username
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: UTF8
  database: thredded_test
  username: username
  password: password
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: UTF8
  database: thredded_production
  username: username
  password: password
  host: localhost
  port: 5432
