defaults: &defaults
  site_name: "My Messageboard"
  email: "My Messageboard Mail-Bot <noreply@mysite.com>"
  subject_prefix: "[My Messageboard] "
  default_site_name: "forum"
  default_messageboard_name: "misc-topics"
  default_messageboard_home: "home"            # => home#index
  # default_messageboard_home: "messageboards" # => messageboards#index
  # default_messageboard_home: "topics"        # => messageboards#show where :messageboard_id == default_messageboard_name

development:
  <<: *defaults
  domain: localhost

test:
  <<: *defaults
  domain: test

production:
  <<: *defaults
  domain: domain.com
